name: health_truck
description: "Health Truck App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Backend
  http: ^1.4.0
  shared_preferences: ^2.5.3
  timezone: ^0.10.1

  # UI+
  get: ^4.7.2
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.2.0
  cupertino_icons: ^1.0.6

  # Notificações
  flutter_local_notifications: ^19.2.1

  # PDF Viewer
  syncfusion_flutter_pdfviewer: ^29.2.10

  # Estado
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/TitilliumWeb-Regular.ttf
        - asset: assets/fonts/TitilliumWeb-Light.ttf
        - asset: assets/fonts/TitilliumWeb-Bold.ttf
          weight: 700
        - asset: assets/fonts/TitilliumWeb-Bold.ttf
          style: italic
